### ISSUE TITLE
Cannot find Google folder ID

### ISSUE THREAD

**Issue by Canorus** [mbrother2/backuptogoogle#14]
##### Detail log:
```
[ 16/02/2020 13:01:11 ] ---
[ 16/02/2020 13:01:11 ] Checking OS...
[ 16/02/2020 13:01:11 ] OS supported
[ 16/02/2020 13:01:12 ] Start upload to Google Drive...
[ 16/02/2020 13:01:12 ] Checking Google folder ID...
[ 16/02/2020 13:11:51 ] [CHECKS][FAIL] Can not find Google folder ID 1M4OdlBWWrm3HarjdloMjAw0eXWtwOuKP . Exit
[ 16/02/2020 13:11:51 ] Sending error email...
[ 16/02/2020 13:11:54 ] Send error email successful
```

```
[ 16/02/2020 12:56:30 ] ---
[ 16/02/2020 12:56:30 ] Creating necessary directory...
[ 16/02/2020 12:56:30 ] Directory /home/canor/.gdrive existed. Skip
[ 16/02/2020 12:56:30 ] Check write to /home/canor/.gdrive successful
[ 16/02/2020 12:56:30 ] Directory /home/canor/bin existed. Skip
[ 16/02/2020 12:56:30 ] Check write to /home/canor/bin successful
[ 16/02/2020 12:56:30 ] Checking OS...
[ 16/02/2020 12:56:30 ] OS supported
[ 16/02/2020 12:56:30 ] Checking necessary package...
/usr/bin/curl
[ 16/02/2020 12:56:30 ] Package curl is installed
/usr/bin/git
[ 16/02/2020 12:56:30 ] Package git is installed
[ 16/02/2020 12:56:30 ] Cheking network...
[ 16/02/2020 12:56:31 ] Connect Github successful
[ 16/02/2020 12:56:31 ] Connect Google successful
[ 16/02/2020 12:56:31 ] Downloading script cron file from github...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16335  100 16335    0     0  37465      0 --:--:-- --:--:-- --:--:-- 37379
[ 16/02/2020 12:56:32 ] Check md5sum for file cron_backup.bash successful
[ 16/02/2020 12:56:32 ] Downloading setup file from github...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16626  100 16626    0     0  36621      0 --:--:-- --:--:-- --:--:-- 36540
[ 16/02/2020 12:56:33 ] Check md5sum for file butgg.bash successful
[ 16/02/2020 12:56:33 ] Downloading go from Google...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  122M  100  122M    0     0  10.2M      0  0:00:11  0:00:11 --:--:-- 10.3M
[ 16/02/2020 12:56:44 ] Extracting go lang...
[ 16/02/2020 12:56:47 ] Cloning gdrive project from Github...
Cloning into 'gdrive'...
remote: Enumerating objects: 1458, done.
remote: Total 1458 (delta 0), reused 0 (delta 0), pack-reused 1458
Receiving objects: 100% (1458/1458), 465.59 KiB | 636.00 KiB/s, done.
Resolving deltas: 100% (873/873), done.
[ 16/02/2020 12:56:49 ] Build your own gdrive!

Read more: https://github.com/mbrother2/backuptogoogle/wiki/Create-own-Google-credential-step-by-step
 Your Google API client_id:
 Your Google API client_secret:

[ 16/02/2020 12:59:02 ] Building gdrive...
[ 16/02/2020 12:59:03 ] Build gdrive successful. Gdrive bin locate here /home/canor/bin/gdrive 
[ 16/02/2020 12:59:03 ] Setting up gdrive credential...
User: ­엄성찬(학부/문과대학 중어중문학), 2011111024@yonsei.ac.kr
Used: 3.3 TB
Free: -3263807690678.0 B
Total: 
Max upload size: 5.2 TB
[ 16/02/2020 12:59:04 ] Setup gdrive credential successful
[ 16/02/2020 12:59:04 ] Setting up config file...

 Which directory on your server do you want to upload to Google Drive?(default /home/canor/backup): 
 How many days do you want to keep backup on Google Drive?(default 7): 

Read more https://github.com/mbrother2/backuptogoogle/wiki/What-is-the-option-SYNC_FILE%3F
 Do you want only sync file(default no)(y/n): 

Read more https://github.com/mbrother2/backuptogoogle/wiki/Get-Google-folder-ID
 Your Google folder ID(default None): 1M4OdlBWWrm3HarjdloMjAw0eXWtwOuKP
 Do you want compress directory before upload?(default no)(y/n): 

Read more https://github.com/mbrother2/backuptogoogle/wiki/Turn-on-2-Step-Verification-&-create-app's-password-for-Google-email
 Do you want to send email if upload error(default no)(y/n): y
 Your Google email user name: helios7157@gmail.com
 Your Google email password: 
 Which email will be receive notify?: helios7157@gmail.com
[ 16/02/2020 13:00:11 ] Setup config file successful

[ 16/02/2020 13:00:11 ] Setting up cron backup...
[ 16/02/2020 13:00:11 ] Cron backup existed. Skip

[ 16/02/2020 13:00:11 ] +-----
[ 16/02/2020 13:00:11 ] | SUCESSFUL! Your information:
[ 16/02/2020 13:00:11 ] | Backup dir      : /home/canor/backup
[ 16/02/2020 13:00:11 ] | Config file     : /home/canor/.gdrive/butgg.conf
[ 16/02/2020 13:00:11 ] | Log file        : /home/canor/.gdrive/butgg.log
[ 16/02/2020 13:00:11 ] | Keep backup     : 7 days
[ 16/02/2020 13:00:11 ] | Google folder ID: 1M4OdlBWWrm3HarjdloMjAw0eXWtwOuKP
[ 16/02/2020 13:00:11 ] | Your email      : helios7157@gmail.com
[ 16/02/2020 13:00:11 ] | Email password  : 
[ 16/02/2020 13:00:11 ] | Email notify    : helios7157@gmail.com
[ 16/02/2020 13:00:11 ] | butgg.bash file : /home/canor/bin/butgg.bash
[ 16/02/2020 13:00:11 ] | Cron backup file: /home/canor/bin/cron_backup.bash
[ 16/02/2020 13:00:11 ] | Gdrive bin file : /home/canor/bin/gdrive
[ 16/02/2020 13:00:11 ] | Cron backup     : 0 0 * * * bash /home/canor/bin/cron_backup.bash >/dev/null 2>&1
[ 16/02/2020 13:00:11 ] | Google token    : /home/canor/.gdrive/token_v2.json
[ 16/02/2020 13:00:11 ] +-----

IMPORTANT: Please run command to use butgg: source /home/canor/.profile 
If you get trouble when use butgg.bash please report here:
https://github.com/mbrother2/backuptogoogle/issues
```

backup script says Google folder with that ID is unable to find but it actually exists. And it used to work before. Any suggestion?

![image](https://user-images.githubusercontent.com/7209435/74599528-d6759c00-50c6-11ea-87ba-0c556fdae8aa.png)

**Comment by mbrother2** [comment]
Hi

Please show the output of command:
```
gdrive list -m 100000 --name-width 0 | grep " dir " | awk '{print $1}' | grep -c "^1M4OdlBWWrm3HarjdloMjAw0eXWtwOuKP$"
```

**Comment by mbrother2** [comment]
@Canorus 

I fixed the issue related to check Google Drive folder ID. Please update butgg.bash with command `butgg.bash --update` then run `cron_backup.bash -v` again.

**Comment by Canorus** [comment]
oh I was just going to say that the command returned `0` 
I'll add after updating the script thanks.

**Comment by Canorus** [comment]
Hi, I tried with updated script but unfortunately it didn't work.

`gdrive list -m 100000 --name-width 0 | grep " dir " | awk '{print $1}' | grep -c "^1M4OdlBWWrm3HarjdloMjAw0eXWtwOuKP$"` still showed `0`. Please let me know if there's anything I should have done while updating the script other than `butgg.bash --update`, like disabling cache or something, and if there's anything else I can try. Thank you so much for taking your time into this. @mbrother2

**Comment by mbrother2** [comment]
@Canorus 

You're welcome! Please show the output of command:
```
gdrive list -m 100000 --name-width 0
```

**Comment by mbrother2** [comment]
@Canorus 

Seem you have more than 100000 files, so butgg.bash script can not check Google Folder ID right. I improved the way to check Google Drive folder ID. Please update butgg.bash with command `butgg.bash --update` then run `cron_backup.bash -v` again.

**Comment by Canorus** [comment]
Hi my apologies for delayed response. Let me just check real quick. thanks. @mbrother2

**Comment by Canorus** [comment]
Hi

I just updated the script and it worked right away. Thank you so much for your hard work. @mbrother2
